name: Deploy to Somee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to Somee (FTP)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          # Các tham số bạn yêu cầu
          protocol: ftp              # Somee chỉ hỗ trợ FTP
          port: 21
          log-level: standard
          timeout: 300000            # 5 minutes
          # Upload tất cả từ repo
          local-dir: "./"
          # Thư mục web đúng của bạn:
          server-dir: "/www.TestFile.somee.com/"
          dangerous-clean-slate: false
