name: Deploy to Somee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source
        uses: actions/checkout@v3

      - name: Upload via FTP to Somee
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SOMEE_FTP_SERVER }}
          username: ${{ secrets.SOMEE_FTP_USERNAME }}
          password: ${{ secrets.SOMEE_FTP_PASSWORD }}
          local-dir: "./"          # thư mục chứa index.html
          server-dir: "/wwwroot/"  # thư mục web của Somee
