name: Deploy to Somee

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy to Somee Hosting (FTP)
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.SOMEE_FTP_SERVER }}
          username: ${{ secrets.SOMEE_FTP_USERNAME }}
          password: ${{ secrets.SOMEE_FTP_PASSWORD }}

          # ==== Các tham số bạn yêu cầu ====
          protocol: ftps           # ftp / ftps
          port: 21                 # Somee dùng port 21
          log-level: standard      # minimal / standard / verbose
          timeout: 300000          # 300000 ms = 5 minutes
          # ================================

          # Thư mục upload từ repo
          local-dir: "./"

          # Thư mục web public trên Somee
          server-dir: "/wwwroot/"

          # Không xóa sạch server
          dangerous-clean-slate: false
